spring.application.name=insta
server.address=0.0.0.0
server.port=${PORT:8081}


server.servlet.context-path=/insta-scrapper

# Default Configuration
resilience4j.ratelimiter.configs.default.limitForPeriod=40
resilience4j.ratelimiter.configs.default.limitRefreshPeriod=10s
resilience4j.ratelimiter.configs.default.timeoutDuration=10ms

# Instance Configuration
resilience4j.ratelimiter.instances.backendRateLimiter.baseConfig=default
resilience4j.ratelimiter.instances.backendRateLimiter.limitForPeriod=40
resilience4j.ratelimiter.instances.backendRateLimiter.limitRefreshPeriod=10s
resilience4j.ratelimiter.instances.backendRateLimiter.timeoutDuration=10ms

